### ISSUE TITLE
stdout.apply is evaluated during a preview

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-command#238] opened 2023-07-26 10:16 UTC
### What happened?

Given a simple python program:

```python
import json

import pulumi
from pulumi_command import local

some = local.Command(
    "some-json",
    create='echo \'{"some": "json"}\'',
).stdout.apply(
    lambda output: json.loads(output)["some"]
)

pulumi.export("some", some)  # this is not actually needed to reproduce the error
```

When `pulumi preview` or `pulumi up` is run, it fails:

```
error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "src/__main__.py", line 10, in <lambda>
        lambda output: json.loads(output)["some"]
                       ^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
```

However `pulumi up --skip-preview --yes` works correctly.

It seems the output lambda is evaluated during the preview, even it shouldn't.

### Expected Behavior

It shouldn't fail - `stdout.apply` shouldn't be evaluated during preview as it is `pulumi.Output`.

### Steps to reproduce

see above

### Output of `pulumi about`

CLI
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME     VERSION
command  0.7.2
python   unknown

Host
OS       arch
Version  "23.0.0"
Arch     x86_64

This project is written in python: executable='.venv/bin/python3' version='3.11.3'

Backend
Name           <REDACTED>
URL            file://.
User           <REDACTED>
Organizations

Dependencies:
NAME            VERSION
pulumi-command  0.7.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-07-27 05:17
Hello @jancespivo,

Thank you for bringing up this issue, and we apologize for any inconvenience you're facing. After reviewing the problem, it appears that this is a duplicate of issue #166, which already has an ongoing discussion. Therefore, we will be closing this particular thread and directing further attention to the original issue.

Rest assured, I will notify the team about this situation once again, with the aim of expediting the process and finding a solution promptly.

**Closed** 2023-07-28 09:10 UTC
Labels: kind/bug, resolution/duplicate
