### ISSUE TITLE
Add support for bastion-based connections

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-command#16] opened 2021-12-14 22:47 UTC
There are cases where the connection to a remote host must be established via a bastion.  We could add support for this in the `remote.Connection` args.

**Comment by AMKamel** [comment] 2022-02-17 06:49
That's pretty much needed

**Comment by JamesMilneFilmlight** [comment] 2022-05-03 21:18
Another plus 1 for this, my existing code using the paramiko-based provider in Python uses the 'gateway' parameter to proxy SSH connections.

**Comment by jsbrain** [comment] 2022-05-07 15:38
Absolutely, this should be highest priority in my opinion.

**Comment by taylorific** [comment] 2023-04-25 21:42
+1

**Comment by thomas11** [comment] 2024-04-25 08:29
This is a duplicate of #131 and was implemented by #269.

**Closed** 2024-04-25 08:29 UTC
Labels: kind/enhancement, resolution/fixed
