### ISSUE TITLE
Consider triggering replacement for CopyFile when local file changes

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-command#151] opened 2022-10-27 15:46 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

CopyFile does not sync the local file to the remote file when the local file changes. This can be implemented manually by using `triggers` with the hash of the local file forcing a replace. But perhaps should be the default behavior? If not, perhaps we can make this trigger example easy to find for new users.

Please see details worked out in the gist: https://gist.github.com/t0yv0/addb78402b3e91a910b2021bce7c8e1d

Also, tangentially, remote.Command that depends_on the CopyFile does not replace when CopyFile replaces. Is this expected? It can be made replace itself if given the same triggers as CopyFile in the current implementation.

**Comment by iwahbe** [comment] 2022-10-31 16:13
`CopyFile` takes a local path string right now. I would be hesitant to add *magic* replacement semantics there. We could and should add the ability to specify an asset instead of a path, which would solve this for us.

**Comment by t0yv0** [comment] 2022-10-31 16:24
That can be a good idea. I think the key here is the default documentation path that folks are looking at should enable the "keep the server file in sync with the local one sceanario" - that seems to me a better "default", even if it's not technically a default and needs some settings added.

**Comment by iwahbe** [comment] 2022-10-31 17:43
I'm thinking something like
```
localPath: string
description: >
  The path to the file to be copied. This should be used only when you
  don't want CopyFile to trigger replacements because of underlying file
  changes.

  Mutually exclusive with `localFile`.

localFile: Asset
description: >
  The file to be copied.

  Mutually exclusive with `localPath`.
```

**Comment by t0yv0** [comment] 2022-10-31 18:24
Can mention the trigger recipe into localPath.

```
If you want the path to sync upon changes, add a trigger to the `triggers` property with with the hash of the file contents.
```

**Comment by lukehoban** [comment] 2022-12-29 01:34
Closing as duplicate of #33 and #42.

**Closed by lukehoban** 2022-12-29 01:34 UTC
Labels: kind/enhancement, resolution/duplicate
