### ISSUE TITLE
 Warnings should not be treated as errors

### ISSUE THREAD

**Issue by andrekiba** [pulumi/pulumi-command#197] opened 2023-05-12 08:17 UTC
### What happened?

I don't have a clear idea about what happens but seems that if the command output has warnings these are treated as errors and, the first time, the pulumi command fails...but the the real command launched succeeds.
For example in this case I triggered an azure container registry quick task with a command like this:
`var azAcrBuildAndPush = Output.Format($"az acr build -t $IMAGENAME -r $REGISTRY -f $DOCKERFILE --build-arg PAT={Output.Unsecret(dockerConfig.RequireSecret("adospat"))} --platform linux/amd64 $CONTEXT");`
and was successful but the pulumi command resource failed the first time
![image](https://github.com/pulumi/pulumi-command/assets/12699760/a5ce7e1d-9614-4a30-8715-8b7bb9cd9ea8)

### Expected Behavior

Do not make the pulumi command fail if the command launched is successful

### Steps to reproduce

Not sure what to do...you can try the same I did for example 

### Output of `pulumi about`

Pulumi              3.54.1
Pulumi.AzureAD      5.37.0
Pulumi.AzureNative  1.102.0
Pulumi.Command      0.5.2
Pulumi.Docker       4.2.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2023-05-12 17:24
Hi @andrekiba - thank you for filing this issue. It's looking like there's a discrepancy between our diagnostics output and the actual behavior.

To be clear, I don't see a failure on your screenshot - can you help us understand what you mean by 

> and, the first time, the pulumi command fails...but the the real command launched succeeds.

Do you mean this pops up as an error on `pulumi preview`?

Finally, if you can help us out by providing a minimal repro of this behavior, that would be awesome.

**Comment by mikhailshilkov** [comment] 2023-08-04 12:40
Since we haven't received a repro since about three months ago, and the problem isn't quite clear either, I'll go ahead and close the issue for now. Please open a new open with a clear repro program if it still persists.

**Closed by mikhailshilkov** 2023-08-04 12:40 UTC
Labels: kind/bug, resolution/no-repro

**Comment by andrekiba** [comment] 2023-08-08 10:29
@mikhailshilkov I'm sorry for my delay on this but I think the problem is still present, I'll try to create an example as soon as possible. Here the images in which you can see that the pulumi command fails but the `az acr build` completed successfully

![acr_command](https://github.com/pulumi/pulumi-command/assets/12699760/cfe75e98-7e44-49d6-9527-50e96c3483b8)

![acr_command1](https://github.com/pulumi/pulumi-command/assets/12699760/0748e067-e4fe-4913-aa5d-e2fb2689a7bf)

![acr_command2](https://github.com/pulumi/pulumi-command/assets/12699760/43b2057d-cc81-4083-abd6-b9e8a63996c5)
